services:
  grav:
    image: lscr.io/linuxserver/grav:latest
    container_name: needless-grav
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
    volumes:
      - ./site:/config
    ports:
      - "8080:80"
    restart: unless-stopped
